### ISSUE TITLE
你们有遇到乱码的问题么？

### ISSUE THREAD

**Issue by huaxulong** [wuda0112/mysql-tester#4]
你们有遇到乱码的问题么？我的全是乱码问题。

**Comment by jiayanbo** [comment]
用户表 username 是乱码的

**Comment by Cyoking** [comment]
遇到了怎么解决鸭？

**Comment by wuda0112** [comment]
麻烦贴下图片，应该不是乱码吧，随机生成的中文，我自己这边试了很多次都是随机中文，里面也有繁体，看上去很像乱码

**Comment by wuda0112** [comment]
从1.0.2版本开始，所有随机生成的字符串都只有英文，不会随机生成中文了，所以不会再有乱码问题
